### ISSUE TITLE
Invalid serialization for rdf:type

### ISSUE THREAD

**Issue by sa-bpelakh** [edmcouncil/rdf-toolkit#15]
`rdf:type` should only be serialized as `a` when it is a predicate, as per [Turtle grammar](https://www.w3.org/TR/turtle/#sec-grammar-grammar), but the sorted serializer does it for subjects and objects as well. This leads to output that cannot be processed by standard-compliant parsers.

For example:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
rdf:type rdf:type rdf:Property .
<prop:list> a rdf:List; rdf:first rdf:type; rdf:rest rdf:nil .
```

should serialize as:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

rdf:type a rdf:Property .
<prop:list>
  a rdf:List ;
  rdf:first rdf:type ;
  rdf:rest rdf:nil  .
```
but instead produces:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

a a rdf:Property .
<prop:list>
  a rdf:List ;
  rdf:first a ;
  rdf:rest rdf:nil .
```
I will be creating a PR momentarily to address this issue.

**Comment by mereolog** [comment]
@sa-bpelakh I will raise this issue with @trojczak who is the developer taking care of this project.

**Comment by trojczak** [comment]
The PR looks fine. I'll close this issue. Thanks for the contribution!
