### ISSUE TITLE
Inconsistent conventions regarding owl:NamedIndividual 

### ISSUE THREAD

**Issue by uscholdm** [edmcouncil/rdf-toolkit#28]
People using Protege to build ontologies end up with all individuals being explicit instances of `owl:NamedIndividual`.  Other tools, and certainly, text editors used to develop ontologies do not. So here is the sort of thing that happens.

1. Jill creates and ontology with a bunch of classes and properties and 10 instances in a text editor, runs it through the serializer and commits it to git. There are no instances of `owl:NamedIndividual`.
2. Jane loads the ontology into Protege, to fix a typo in a single `skos:definition` for one of the classes and saves the ontology, serializes it and commits it to git. 

Git thinks there are 11 changes, when there is really only one that matters. 
SUGGESTION: have an option to suppress all instances of `owl:NamedIndividual`

**Comment by trojczak** [comment]
Hi, @uscholdm!
At the first glance, I think it is possible to implement this, but I have to spend more time confirming it. Are you still interested in having this change in rdf-toolkit?

**Comment by uscholdm** [comment]
Yes, very much so, thank you.

**Comment by abcoates** [comment]
I believe it should be the case that you can add owl:NamedIndividual as a type to any individual that isn't anonymous, i.e. which has a URI or QName assigned to it.

**Comment by uscholdm** [comment]
> I believe it should be the case that you can add owl:NamedIndividual as a type to any individual that isn't anonymous, i.e. which has a URI or QName assigned to it.

Perhaps, but I'm interested in getting rid of them all, as they are superfluous to my needs and make collaborative ontology development becaues some tools add them and some do not. Protege adds them. Some people may like them, so maybe options to include all or remove all or leave exactly as they are?  Others may like those options.

**Comment by ElisaKendall** [comment]
I would rather make it optional - we preserve these as an explicit declaration in FIBO, our pharma effort, and the IOF manufacturing ontology effort.  But an option that removes them and/or preserves them might be useful.

**Comment by trojczak** [comment]
Hi, @uscholdm!

Could you provide an example of an ontology that doesn't use `owl:NamedIndividual` for defining named individuals? It would be helpful to make sure that we think about the same expected output.

**Comment by rjyounes** [comment]
This option has been added to the src and the readme. When do you plan to update the jar file at the download link?

**Comment by trojczak** [comment]
Hi, @rjyounes! I've added a new release for the newest version of RDF Toolkit: https://github.com/edmcouncil/rdf-toolkit/releases/tag/v1.14.0
Hope this helps.

**Comment by rjyounes** [comment]
That's great! Thanks very much, @trojczak.

**Comment by rjyounes** [comment]
I am getting the following error when I run the latest version:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

You can find troubleshooting information at the following URL: `https://www.slf4j.org/codes.html`.

In addition to getting the error message, the `-sni` option is not working, though the other serialization functions are.

**Comment by rjyounes** [comment]
I am not able to get this to work. I'm using the following command:

```
java -jar rdf-toolkit-1.14.0.jar -sdt explicit -dtd -ibn -sni -s gistCore.ttl -t gistCore.tmp.ttl
```

The output file and input file are identical except for whitespace. I'm attaching both files for reference.

[gist.zip](https://github.com/edmcouncil/rdf-toolkit/files/10069104/gist.zip)

**Comment by trojczak** [comment]
Hi, @rjyounes!
To make sure that we are on the same page, could you provide the following examples of serializations (fragments with one example individual should be enough):
1. containing the input serialization (how it looks before using Protege),
2. after saving file with Protege,
3. how it should look after running RDF Toolkit on the file serialized by Protege.

Thanks!

**Comment by rjyounes** [comment]
Hi @trojczak,

I don't generally use Protege, but I'm attaching a zip file with four files:
* `namedIndividual.ttl`: Hand-written turtle file with `owl:NamedIndividual` assertion.
* `namedIndividual.serialized`: Above file after serialization.
* `namedIndividual.protege.ttl`: Output from Protege after loading `namedIndividual.ttl`.
* `namedIndividual.protege.serialized.ttl`: Above file after serialization.

I'm running rdf-toolkit with this command:

```
java -jar rdf-toolkit-1.14.1.jar -tfmt turtle -sdt explicit  -ibn -sni -s namedIndividual.ttl -t namedIndividual.serialized.ttl
```
[namedIndividual.zip](https://github.com/edmcouncil/rdf-toolkit/files/10238534/namedIndividual.zip)

Thanks for your help.

Rebecca

**Comment by smeapa** [comment]
Hi,Please can you remove me from this mail list. Many thanks,Paul Smeaton-Russell Sent from my iPhoneOn 16 Dec 2022, at 1:01 am, Rebecca Younes ***@***.***> wrote:﻿
Hi @trojczak,
I don't generally use Protege, but I'm attaching a zip file with four files:

namedIndividual.ttl: Hand-written turtle file with owl:NamedIndividual assertion.
namedIndividual.serialized: Above file after serialization.
namedIndividual.protege.ttl: Output from Protege after loading namedIndividual.ttl.
namedIndividual.protege.serialized.ttl: Above file after serialization.

I'm running rdf-toolkit with this command:
java -jar rdf-toolkit-1.14.1.jar -tfmt turtle -sdt explicit  -ibn -sni -s namedIndividual.ttl -t namedIndividual.serialized.ttl

namedIndividual.zip
Thanks for your help.
Rebecca

**Comment by mereolog** [comment]
@rjyounes we believe that we have rectified the problem - could you check?

**Comment by trojczak** [comment]
Hi, @rjyounes! I've added a new release with the change @mereolog mentioned: https://github.com/edmcouncil/rdf-toolkit/releases/tag/v1.14.2

**Comment by rjyounes** [comment]
Hi @trojczak that did the trick - thank you!
