### ISSUE TITLE
SLF4J StaticLoggerBinder warning

### ISSUE THREAD

**Issue by rjyounes** [edmcouncil/rdf-toolkit#40]
I am getting the following error when I run either v1.11.0 or v1.14.0:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

You can find troubleshooting information at the following URL: `https://www.slf4j.org/codes.html`.

**Comment by ElisaKendall** [comment]
@mereolog I'm getting this same issue today as well. I had not seen it until this morning, however. It blocks commits, so it needs to be addressed ASAP.
