### ISSUE TITLE
The RDF toolkit incorrectly revises IRIs for those with non-standard structure

### ISSUE THREAD

**Issue by ElisaKendall** [edmcouncil/rdf-toolkit#47]
When serializing IRIs such as those found in the Qlaira example for the IDMP project (i.e., any IRI that is associated with the SPOR repository managed by the European Medicines Agency), the serializer incorrectly re-writes some of the abbreviated IRIs and completely replaces others with the full string value of the IRI.  Certain SPOR product IRIs were changed from "spor-p;" to "spor-p;/products/", and similarly with "spor-s;" replaced with "spor-s;/substances/". The replacements tend to occur in the named class or individual rather than other references to them.

See the Qlaira Example ontology in IDMP/EXT/Examples.

**Comment by trojczak** [comment]
Hi, Elisa!

It seems that the problem occurs because the IRI of the ontology used by some entities has the following format: `https://spor.ema.europa.eu/smswi/#/products/`. It seems to me that according to the IRI standard, the `#` char should be used to delimit the namespace and the fragment (an identifier) of an entity's IRI (see: https://datatracker.ietf.org/doc/html/rfc3987#section-2.2)

So, it is expected that the division should be like that:

```
Namespace: "https://spor.ema.europa.eu/smswi/#" Fragment: "/products/00006006"
```

and not like this (as it is currently in this ontology):

```
Namespace: "https://spor.ema.europa.eu/smswi/#/products/" Fragment: "00006006"
```

And rdf-toolkit tries to act according to this standard.

Shouldn't this be somehow addressed by the authors of this ontology, and not in the rdf-toolkit?

**Comment by ElisaKendall** [comment]
@trojczak Hi Rafal,

Although the IRIs are non-standard, if there is some way to address this for cases that include '/#/' in the name, maybe a speclal "switch", we need to be able to generate something consistently. I've tried it both ways, the way it is now and the way you've suggested, and it's not clear that it is consistent in either case. These IRIs are specific to the European Medicines Agency SPOR data, but it is a really important use case for our IDMP project.  and, what Protege and other tools do with it when they consume it is also inconsistent. 

These are slash-style IRIs that include an embedded "#" unfortunately, so they do not follow any of the patterns that are specified in the 'Cool IRIs for the Semantic Web' or other W3C recommendations - the "#" style IRI should not have anything other than the local name after the "#" per the W3C, ad "#" is reserved in RDF for those IRIs that are "hash style", so there is an inconsistency in the way that EMA produces their data. If we can add a check for cases where there is a "slash style" IRI that includes an embedded "#", and in that case produce what the ontologist decide the proper prefix for the ontology is, which is in the header of the ontology (regardless of serialization in turtle or RDF/XML) that would be better.  I'm ok if this requires some kind of additional optional switch for the serializer, but we really need this for the IDMP project since it is prevalent in the EU public data. Doing this manually is time consuming and not the best use of my time, for example, and I was forced to upload the ontology bypassing the serializer, which is not ideal.
