### ISSUE TITLE
download the rdf-toolkit

### ISSUE THREAD

**Issue by lavhal** [edmcouncil/rdf-toolkit#5]
Hi,

I'm trying to download the rdf-toolkit, but unable to do that. After login with my GitHub credentials, it redirect me to a Jenkins page where I get the message: Access Denied: ... is missing the Overall/Read permission.

How can I download this tool?

**Comment by obkhan** [comment]
Odd - can you try this link?
It's the same from the page, I just tested it last night in fact and again this a.m. was able to download it. 
https://jenkins.edmcouncil.org/job/rdf-toolkit-build/lastSuccessfulBuild/artifact/target/scala-2.11/rdf-toolkit.jar

**Comment by lavhal** [comment]
Maybe I'm doing something wrong, but I'm receiving the same message also with this link.

**Comment by dallemang** [comment]
I thought that Jenkins had the same credentials as github, but I think you
do have to log in again.

I see the user name lavhal in our jenkins server, so I don't know why those
credentials aren't working.

Maybe we need to escalate to Jacobus to figure this out?

**Comment by obkhan** [comment]
Not having access to Jenkins to assist ... perhaps this would help Jacobus? 
http://stackoverflow.com/questions/22717773/jenkins-github-authentication-error-user-is-missing-the-overall-read-permission

In the meantime is there a way we can share the file by other means?  to lavhal? I don't use dropbox nor google docs or any file sharing service but something like that may be a temporary solution or even e-mailing the jar file

**Comment by lavhal** [comment]
I tried to login/logout and with different browsers but unfortunately, the same message is appearing. 
Related to sharing methods, maybe you can put it to this GitHub repo or as you suggested in one of the services: Google Drive or Dropbox, which is more convenient for you.

Thanks in advance.

**Comment by osma** [comment]
I'm having the exact same problem. Jenkins says 

```
Access Denied
osma is missing the Overall/Read permission
```

I'm not affiliated with the project in any way, I'm just interested in trying out the sorted Turtle serialization. I guess I could compile this myself from source but it would be easier if the JAR download worked.

**Comment by dallemang** [comment]
I have forwarded this to Tony Coates, who maintains the serializer.  I'll have him post here when we figure out what's going on.

**Comment by lavhal** [comment]
Thanks a lot, I already compiled from the sources. But it will be good for the others to have an easy download option.

**Comment by oldskeptic** [comment]
All links currently getting a 404 for the jar file.
