### ISSUE TITLE
rdf-toolkit discards information

### ISSUE THREAD

**Issue by justin2004** [edmcouncil/rdf-toolkit#57]
testcase2.ttl:
```turtle
@prefix ex: <https://ex.com/> .

_:b66 ex:a ex:Execution ;
   ex:produces _:b67  .

_:b67 ex:a ex:ContentExpression .

_:b0 ex:a ex:File ;
  ex:hasPart _:b67 .
```

```sh
java -jar ~/Downloads/rdf-toolkit-1.14.2.jar -tfmt turtle -sdt explicit -dtd -ibn -sni -s testcase2.ttl -t testoutput.ttl
```

produces:
```turtle
@prefix ex: <https://ex.com/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

[]
        ex:a ex:Execution ;
        ex:produces [
                ex:a ex:ContentExpression ;
        ] ;
        .

[]
        ex:a ex:File ;
        ex:hasPart [
                ex:a ex:ContentExpression ;
        ] ;
        .
```

which discards the fact that the blank node _:b67 is the same thing that is the part of the file.
rdf-toolkit makes it look like the part of the file could be the thing produced by the execution or not.

see how apache jena does not discard that fact:
```sh
$ ~/Downloads/apache-jena-4.9.0/bin/riot --formatted=turtle testcase2.ttl
```
produces
```turtle                
@prefix ex: <https://ex.com/> .

[ ex:a         ex:Execution;
  ex:produces  _:b0
] .

[ ex:a        ex:File;
  ex:hasPart  _:b0
] .

_:b0    ex:a    ex:ContentExpression .
```

see how it does not discard the fact that the file has a specific part _:b0

in this case, rdf-tool kit isn't wrong, but it is discarding information.
by that i mean the input data says "X is the case" and the output of rdf-toolkit says "X is or is not the case."

**Comment by mereolog** [comment]
@justin2004, imho, jena does not consistently run our option -ibn because _:b0 is not formatted as an inline blank node in the last line of the output.

Running rdf-toolkit without -ibn parameter keeps the node identity - see also https://github.com/edmcouncil/rdf-toolkit/issues/55#issuecomment-1770417649.
