### ISSUE TITLE
Unable to publish my branch

### ISSUE THREAD

**Issue by ElieA-L** [edmcouncil/rdf-toolkit#6]
@jgeluk When I try to publish my branch (a copy of scala-owlapi-based-serializer for the purpose of updating the artifact ontology), I get the following message:
"You may not have permission to access rdf-toolkit. Check Preferences to make sure you’re still logged in."
Can you help?
Thanks.

**Comment by ElieA-L** [comment]
@DennisWisnosky made permission changes and I am not able to commit my changes. I am closing this now.

**Comment by pgericson** [comment]
Have you created a pull request? or pushed directly to this repository? as the normal change process would be, fork this repo -> change code -> push to your own repo -> create pull request to the edmcouncil/rdf-toolkit -> merge into edmcouncil/rdf-toolkit -> Done

If this is what you have done, ignore this message.

**Comment by ElieA-L** [comment]
@pgericson When I tried to pull I was getting an error: not enough permission. After my permissions on the repo were updated, Dennis asked me to sync. My guess is that it synced with the main repo and not a fork (as I haven't forked it). I will change my workflow to the one you describe above. Thx.
