### ISSUE TITLE
rdf-toolkit replaces "-x-" in private use language subtags with "-X-"

### ISSUE THREAD

**Issue by rjyounes** [edmcouncil/rdf-toolkit#60]
Private use subtags are represented with lowercase "-x-"; see https://www.w3.org/International/articles/language-tags/. My specific use case is the tag "bo-x-ewts" for Extended Wylie transliteration of Tibetan. The uppercasing of the "x" is turning this into a malformed private use tag that will not be recognized by the community.

**Comment by mereolog** [comment]
Yes, this is obviously a bug - we will fix it soon.
@rjyounes thanks for your feedback - much appreciated.
