### ISSUE TITLE
CURIE with / not supported

### ISSUE THREAD

**Issue by sahuguet** [edmcouncil/rdf-toolkit#74]
The tool does not seem to accept URIs like `s:1/employees/1`.

When using RdfFormatter (rdf-toolkit version 2.0) 

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix s: <http://acme.org/departments/1/employees/> .
s:1 a foaf:Person .
```
works.

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix s: <http://acme.org/departments/> .
s:1/employees/1 a foaf:Person .
```
does not.

When I use angle brackets
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix s: <http://acme.org/departments/> .
<s:1/employees/1> a foaf:Person .
``` 
works and gets rewritten as
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix s: <http://acme.org/departments/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

s:1/employees/1
	a foaf:Person ;
	.
```

But the rewritten file is not accepted by rdf-toolkit.

**Comment by mereolog** [comment]
As far as I can tell, `s:1/employees/1` is not a well-formed qname because '/' is not in the scope of https://www.w3.org/TeamSubmission/turtle/#nameChar.

You can verify this yourself using a Turtle validator, e.g., http://ttl.summerofcode.be.
